name: Build Data

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
  pull_request:
    branches:
      - main
    paths:
      - 'data/**'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Setup UV
        uses: astral-sh/setup-uv@v8.1.0
        with:
          activate-environment: "true"
          enable-cache: "true"

      - name: Load project deps
        run: |
          uv sync
          uv pip install -e .

      - name: Run QA
        run: |
          python -m tools.qa
  data_build:
    runs-on: ubuntu-latest
    needs: [ "qa" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Setup UV
        uses: astral-sh/setup-uv@v8.1.0
        with:
          activate-environment: "true"
          enable-cache: "true"

      - name: Load project deps
        run: |
          uv sync
          uv pip install -e .

      - name: Run INSP Build
        run: |
          python -m tools.build_geojson
      
      - name: Run CDC Build
        run: |
          python -m tools.build_cdc

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "Latest Data"
          path: "build/"
          archive: true
      